export const legionaries = [
    {
      name: "Faraonqbg",
      rank: "Praetor",
      legion: "OG",
    },
    {
      name: "Mis_ok",
      rank: "Centurio",
      legion: "OG",
    },
    {
      name: "Dudie",
      rank: "Praefectus",
      legion: "OG",
    },
    {
      name: "Leora",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Mis_ok",
    },
    {
      name: "Tredmus",
      rank: "Praetor",
      legion: "Second",
    },
    {
      name: "Marto98",
      rank: "Praefectus",
      legion: "Second",
    },
    {
      name: "Ganfi",
      rank: "Praetor",
      legion: "First",
    },
    {
      name: "Legolas_b",
      rank: "Praefectus",
      legion: "First",
    },
    {
      name: "Ciara_.",
      rank: "Centurio",
      legion: "OG",
    },
    {
      name: "Morskasirena",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Mis_ok",
    },
    {
      name: "Barborko",
      rank: "Centurio",
      legion: "OG",
    },
    {
      name: "Tanq_13",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Ciara_.",
    },
    {
      name: "Freudiana",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Ciara_.",
    },
    {
      name: "Harpy",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Ciara_.",
    },
    {
      name: "Barborka",
      rank: "Centurio",
      legion: "OG",
    },
    {
      name: "Leire",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Mis_ok",
    },
    {
      name: "Compeador",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Ciara_.",
    },
    {
      name: "Eve89",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Ciara_.",
    },
    {
      name: "Angelov76",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Barborko",
    },
    {
      name: "Lotor",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Barborka",
    },
    {
      name: "Vimes",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Barborko",
    },
    {
      name: "Elite.crewxd",
      rank: "Centurio",
      legion: "OG",
    },
    {
      name: "Kokicha",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Barborko",
    },
    {
      name: "Direwolfdido",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Barborko",
    },
    {
      name: "Fars",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Mis_ok",
    },
    {
      name: "Atinapalada_ii",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Mis_ok",
    },
    {
      name: "Ponko",
      rank: "Legionarius",
      legion: "OG",
      reportsTo: "Elite.crewxd",
    },
    {
      name: "Mircata",
      rank: "Legionarius",
      reportsTo: "Barborka",
      legion: "OG",
    },
    {
      name: "Krisinka",
      rank: "Legionarius",
      reportsTo: "Barborka",
      legion: "OG",
    },
    {
      name: "Lepeasant",
      rank: "Legionarius",
      reportsTo: "Barborka",
      legion: "OG",
    },
    {
      name: "Drakan.",
      rank: "Legionarius",
      reportsTo: "Elite.crewxd",
      legion: "OG",
    },
    {
      name: "Divaks",
      rank: "Legionarius",
      reportsTo: "Barborka",
      legion: "OG",
    },
    {
      name: "Aleksandur",
      rank: "Legionarius",
      reportsTo: "Elite.crewxd",
      legion: "OG",
    },
    {
      name: "Steisi",
      rank: "Legionarius",
      reportsTo: "Elite.crewxd",
      legion: "OG",
    },
    {
      name: "Varxovenyjas",
      rank: "Legionarius",
      reportsTo: "Elite.crewxd",
      legion: "OG",
    },
    {
      name: "Senator_",
      rank: "Legionarius",
      reportsTo: "Barborko",
      legion: "OG",
    },
    {
      name: "I_ivanov",
      rank: "Legionarius",
      reportsTo: "Barborko",
      legion: "OG",
    },
    {
        name: "Gimgi",
        rank: "Centurio",
        legion: "First",
    },
    {
        name: "Growni",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Gimgi",
    },
    {
        name: "Evangelist.",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Gimgi",
    },
    {
        name: "Kolyo",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Gimgi",
    },
    {
        name: "Sahsa",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Gimgi",
    },
    {
        name: "Arazortep",
        rank: "Centurio",
        legion: "First",
    },
    {
        name: "Unspoken",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Gimgi",
    },
    {
        name: "Falishmi",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Prusiyski",
    },
    {
        name: "Adriana",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Prusiyski",
    },
    {
        name: "Gron",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Arazortep",
    },
    {
        name: "Dreb4o",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Arazortep",
    },
    {
        name: "Crazyhacker",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Prusiyski",
    },
    {
        name: "Hadroy",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Prusiyski",
    },
    {
        name: "Alienes",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Arazortep",
    },
    {
        name: "Gorskiq",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Arazortep",
    },
    {
        name: "Zzorov99",
        rank: "Legionarius",
        legion: "First",
        reportsTo: "Arazortep",
    },
    {
        name: "Prusiyski",
        rank: "Centurio",
        legion: "First",
        reportsTo: "Arazortep",
    },
    {
        name: "Shizola",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Krasiko",
    },
    {
        name: "Krasiko",
        rank: "Centurio",
        legion: "Second",
    },
    {
        name: "Maximko",
        rank: "Centurio",
        legion: "Second",
    },
    {
        name: "F3lizz",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Krasiko",
    },
    {
        name: "Jenaoh",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Krasiko",
    },
    {
        name: "Kankrum",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Krasiko",
    },
    {
        name: "Temptation",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Krasiko",
    },
    {
        name: "Anatema",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Krasiko",
    },
    {
        name: "Kokor4o",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Maximko",
    },
    {
        name: "Katyaa",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Maximko",
    },
    {
        name: "Chakalat",
        rank: "Legionarius",
        legion: "Second",
        reportsTo: "Maximko",
    },
    {
      name: "Bikini",
      rank: "Legionarius",
      legion: "First",
      reportsTo: "Prusiyski",
    },
    {
      name: "Gabobg",
      rank: "Legionarius",
      legion: "First",
      reportsTo: "Arazortep",
    },
    {
      name: "Mayora",
      rank: "Legionarius",
      legion: "First",
      reportsTo: "Gimgi",
    },
    {
      name: "Veneno",
      rank: "Legionarius",
      legion: "Second",
      reportsTo: "Maximko",
    },
    {
      name: "Panayot",
      rank: "Legionarius",
      legion: "Second",
      reportsTo: "Maximko",
    },
  ];

  export const legionariesCount = legionaries.length;